---
title: "site-selector"
author: "Molly Bell"
date: "2023-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# set working dir
knitr::opts_knit$set(root.dir = here::here())
   # sets the working directory to where the project file is 
```

```{r}
# load required packages
package.list <- c('plotly',
                  'dplyr',
                  'tidyr',
                  'ggplot2'
)
packageLoad <- function(packages){
  for (i in packages) {
    if (!require(i, character.only = TRUE)) {
      install.packages(i)
      library(i, character.only = TRUE)
    }
  }
}
packageLoad(package.list)
```

```{r}
# Uploading file-merge code to create data frame
source('./Code/file-merger.R')

# create data frame
dat <- returnAllFiles(d = directory, export = FALSE)
# make columns lowercase so they are all the same case
colnames(dat) <- tolower(names(dat))
```

```{r, include=FALSE}

# Site list
  # To select site uncomment location of interest
# loc = ARDEC 2200
loc = 'AVRC STAR'
# loc = 'Barley'
# loc = 'Berthoud'
# Big Hollow
# Boulder Lake
# Below Stagecoach Dam
# Gunnison
# Kerbel
# Legacy
# Molina
# Morrison Creek
# Stage Coach Above
# Stage Coach In
# Stagecoach
# The Ranch
# Upper Yampa
# Yellow Jacket

```

```{r}
# function to save site data as csv
csv_data <- function(dat, location_name) {
  location_data <- dat %>%
    filter(location.name == location_name)
  #create output folder
  folder_name <- "site_selector_temporary_results"
  if (!file.exists(folder_name)) {
    dir.create(folder_name)
  }
  
  file_name <- paste0(folder_name, "/", location_name, "_data_", format(Sys.Date(), "%Y-%m-%d"), ".csv")
  write.csv(location_data, file = file_name, row.names = FALSE)
}
# use the function to save
csv_data(dat, loc)
```

```{r}

# plotly plot with dropdown
create_violin_plot <- function(df, selected_location) {
  y_axis_var_names <- unique(df$analyte)
  
   event_colors <- c("Inflow" = "#E69F00", "Outflow" = "#56B4E9", "Point Sample" = "#009E73")
  
  create_buttons <- function(df, y_axis_var_name, selected_location) {
    list(
      method = 'restyle',
      args = list('y', list(df[df$analyte == y_axis_var_name & df$location.name == selected_location, "result"])),
      label = sprintf('Show %s', y_axis_var_name)
    )
  }
  
  location_violin_plot <- plot_ly(df, x = ~event.type,
                                  y = ~result,
                                  color = ~event.type,
                                  colors = event_colors,
                                  type = 'violin', box = list(
                                    visible = T
                                  ),
                                  meanline = list(
                                    visible = T
                                  )) %>%
    layout(
      title = paste("Violin plots for Location:", selected_location),
      xaxis = list(title = "Collected", tickformat = "%y-%m-%d"),
      yaxis = list(title = "Result"),
      showlegend = TRUE,
      updatemenus = list(
        list(
          buttons = lapply(y_axis_var_names, create_buttons, df = df, selected_location = selected_location)
        )
      ))
  
  return(location_violin_plot)
}
create_violin_plot(dat, loc)

```


```{r}
create_scatterplot_matrix <- function(data, location_nameumn) {
  library(ggplot2)
  
  # Define event type colors
  event_colors <- c("Inflow" = "#E69F00", "Outflow" = "#56B4E9", "Point Sample" = "#009E73")
  
  # Subset data for the specified location
  specific_location_data <- data[data[[location_nameumn]] == unique(data[[location_nameumn]]), ]
  
  # Create a custom panel function for scatterplots with points and histograms
  custom_panel <- function(x, y, ...) {
    # Scatterplot with points
    points(x, y, col = event_colors[specific_location_data$event.type])
    
    # Histogram on the diagonal
    if (x == y) {
      h <- hist(x, plot = FALSE)
      y_density <- density(x)
      y_scale <- max(h$counts) * 0.05
      lines(y_density$x, y_density$y * y_scale, col = "blue")
    }
  }
  
  # Create a scatterplot matrix using pairs() with the custom panel function
  pairs(specific_location_data[c("collected", "result")],
        lower.panel = custom_panel,
        upper.panel = NULL, diag.panel = NULL)
  
  # Calculate correlations
  cor_matrix <- cor(specific_location_data[c("collected", "result")])
  
  # Add correlations above the scatterplot matrix
  n <- ncol(cor_matrix)
  for (i in 1:n) {
    for (j in 1:n) {
      if (i < j) {
        corr <- round(cor_matrix[i, j], 2)
        text(i - 0.2, j + 0.2, labels = corr)
      }
    }
  }
}

# Call the function with your data and desired location column
create_scatterplot_matrix(dat, loc)

```

